import type { Metadata } from "next";
import { Home } from "@/views";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function HomePage() {
  return <Home />;
}
